// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjtdfypfcwgxkxftnozy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqdGRmeXBmY3dneGt4ZnRub3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTE3NTIsImV4cCI6MjA3MDAyNzc1Mn0.dBVtyvC1vGm_PVLHOQ-8a4c3egrzksrLM25z0Vlo7gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});